version: '3.4'

services:
  netcore:
    image: "sumindaniro/netcore"
    depends_on:
      - db
    ports:
      - "80"
    environment:
      DB_SERVER: "db"
      DB_NAME: "BloggingDb"
      DB_USER: "sa"
      DB_PASSWORD: "Auxenta2018!"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Auxenta2018!"
        ACCEPT_EULA: "Y"